### ISSUE TITLE
RuntimeError: Graph disconnected

### ISSUE THREAD

**Issue by alyato** [LawnboyMax/keras_ensemblng#1]
@LawnboyMax 
hi, i met this situation.

> RuntimeError: Graph disconnected: cannot obtain value for tensor Tensor("input_1_3:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_1". The following previous layers were accessed without issue: []

i check the code,and it seem that the `Model` in the `ensemble` `function`
how to change it ?

here is my code:

> model_input= Input(shape=(224,224,3))

> model_vgg = model_from_json(open('model_472.json').read())
   model_vgg.load_weights('weights_472.h5')

> model_inc = model_from_json(open('model_473.json').read())     model_inc.load_weights('weights_473.h5')

> model_dense = model_from_json(open('model_47.json').read())
   model_dense.load_weights('weights_47.h5')
models = [model_vgg,model_inc,model_dense]

when i call the `ensemble` function:

> def   ensemble(models,model_input):
        outputs = [model.outputs[0] for model in models]
         y = Average()(outputs)
        model = Model(model_input,y,name='ensemble')
        return mode
     ensemble_model = ensemble(models,model_input)

i also check similar issue.
i change that `Model(inputs=[model_input,model_input,model_input],y,name='ensemble'`,it doesn't work.
Do you give some suggestions.
thanks.

**Comment by xuzhang5788** [comment]
@alyato @mmxmb 
I have the same problem. Please share your solutions if you solved this problem. Many thanks.
